repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-toml

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.45.0
    hooks:
      - id: eslint
        files: \.(js|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.45.0
          - eslint-plugin-security@1.7.1
          - "@typescript-eslint/eslint-plugin@6.0.0"
          - "@typescript-eslint/parser@6.0.0"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, markdown]

  - repo: local
    hooks:
      - id: rust-lint
        name: Rust Linting
        entry: bash -c 'cd src-tauri && cargo fmt -- --check && cargo clippy -- -D warnings'
        language: system
        pass_filenames: false
        files: \.rs$

      - id: npm-audit
        name: NPM Security Audit
        entry: npm run security:audit
        language: system
        pass_filenames: false

      - id: cargo-audit
        name: Cargo Security Audit
        entry: bash -c 'cd src-tauri && cargo audit'
        language: system
        pass_filenames: false
        
      - id: check-capabilities
        name: Check Tauri Capabilities
        entry: python ./scripts/check_capabilities.py
        language: system
        pass_filenames: false 