name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false  # Don't attempt to fetch submodules
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install cargo-audit
        run: cargo install cargo-audit
        
      - name: Rust Security Audit
        run: cd src-tauri && cargo audit
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies and create lock file
        run: npm install
        
      - name: Check for lock file
        run: |
          if [ ! -f package-lock.json ] && [ ! -f yarn.lock ]; then
            echo "Error: No lock file found." >&2
            exit 1
          fi
        
      - name: NPM Security Audit
        run: npm audit --production

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false  # Don't attempt to fetch submodules
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      
      - name: Format Rust code
        run: cd src-tauri && cargo fmt
      
      - name: Rust Formatting Check
        run: cd src-tauri && cargo fmt -- --check
      
      - name: Rust Clippy Check
        run: cd src-tauri && cargo clippy -- -D warnings
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install
      
      - name: ESLint Check
        run: npm run lint
      
      - name: Prettier Check
        run: npm run format:check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false  # Don't attempt to fetch submodules
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Set PKG_CONFIG_PATH
        run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
      
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      
      - name: Rust Tests
        run: cd src-tauri && cargo test
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install
      
      - name: Frontend Tests
        run: npm test

  build:
    name: Build (${{ matrix.platform }})
    runs-on: ${{ matrix.os }}
    needs: [security-audit, lint, test]
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - platform: windows-latest
            os: windows-latest
          - platform: macos-latest
            os: macos-latest
          - platform: ubuntu-latest
            os: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false  # Don't attempt to fetch submodules
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install
      
      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
      
      - name: Set PKG_CONFIG_PATH
        if: matrix.platform == 'ubuntu-latest'
        run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
      
      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      
      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "Tauri App v__VERSION__"
          releaseBody: "See the assets to download this version and the changelog for details."
          releaseDraft: true
          prerelease: false 